name: EntitySize
version: '${version}'
main: com.maximde.entitysize.EntitySize
author: MaximDe
description: Change the size of an entity
api-version: '1.20'

commands:
  entitysize:

permissions:
  entitysize.commands:
    description: Allows the use of the entitysize command
    default: true
  entitysize.player:
    description: Allows the use of the player subcommand
    default: false
  entitysize.entity:
    description: Allows the use of the entity subcommand
    default: false
  entitysize.reload:
    description: Allows the use of the reload subcommand
    default: false
  entitysize.reset:
    description: Allows the use of the reset subcommand
    default: true
  entitysize.reset.player:
    description: Allows the ability to reset any player
    default: false
  entitysize.reset.all:
    description: Allows the ability to reset all players, using @a
    default: false
  entitysize.self:
    description: Allows the use of the self subcommand
    default: true
  entitysize.entity.looking:
    description: Allows selecting the entity being looked at
    default: false
  entitysize.entity.tag:
    description: Allows selecting the entity by tag
    default: false
  entitysize.entity.name:
    description: Allows selecting the entity by name
    default: false
  entitysize.entity.uuid:
    description: Allows selecting the entity by uuid
    default: false
  entitysize.entity.range:
    description: Allows selecting the entity by range
    default: false
